env:
  browser: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - jsx-a11y
  - unused-imports
  - import
rules:
  sort-imports: off
  import/order:
    # - error
    # - groups:
    #     - builtin
    #     - external
    #     - internal
    #   alphabetize:
    #     order: asc

    [
      "error",
      {
        newlines-between: "never",
        groups: [
          "external",
          "builtin",
          "internal",
          "parent",
          "sibling",
          "index",
          "object",
          "type"
        ],
        pathGroups: [
          {
            pattern: "@/config",
            group: "builtin",
            position: "after"
          },
          {
            pattern: "@/const",
            group: "builtin",
            position: "after"
          },
          {
            pattern: "@/lib",
            group: "builtin",
            position: "after"
          },
          {
            pattern: "@/providers",
            group: "builtin",
            position: "after"
          },
          {
            pattern: "@/hooks",
            group: "builtin",
            position: "after"
          },
          {
            pattern: "@/components",
            group: "builtin",
            position: "after"
          },
        ],
        alphabetize: {
          order: "asc",
          caseInsensitive: true
        }
      }
    ]
  import/no-anonymous-default-export: off
  unused-imports/no-unused-imports-ts: warn
  no-magic-numbers: [1, { ignore: [0, -1], ignoreArrayIndexes: true, ignoreDefaultValues: true }]
  no-console: 1
  quotes: [ 1, 'single', { 'allowTemplateLiterals': true } ]
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/react-in-jsx-scope: off
  react/self-closing-comp: [error, { component: true, html: true }]
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/array-type': [error, { default: array }]
  '@typescript-eslint/naming-convention':
    [
      error,
      {
        selector: interface,
        format: [PascalCase],
        custom: { regex: '^I[A-Z]', match: false },
      },
      {
        selector: typeAlias,
        format: [PascalCase],
        custom: { regex: '^T[A-Z]', match: false },
      },
    ]
